## from https://distillery.rbind.io/posts/2021-03-18-use-github-actions-with-r-markdown-and-distill/
name: Render & Deploy Site
on: [push]
# on:
#  schedule:
#    - cron: '*/10 * * * *'
# for reports '30 12 * * 1,2,3,4,5'
jobs:
  render:
    name: Render README
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-r@v1
        with:
          r-version: '4.0.4'
      - name: sample
        run: Rscript -e 'print("hello")'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Render Site
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      - name: Commit results
        run: |
          git add -A 
          git commit -m 'update readme' || echo "No changes to commit"
          git pull origin
          git push origin || echo "No changes to commit"